apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  namespace: default
spec:
  selector:
    matchLabels:
      run: service3
  template:
    metadata:
      labels:
        run: service3
    spec:
      containers:
        - image: crinehart/nginx:service3
          name: service3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
